---
# Ensure gnu-netcat in not installed
# Nothing wrong with gnu-netcat1 but the ArchLinux wiki seems to recommend openbsd-net
# https://wiki.archlinux.org/title/libvirt#Configuration
# removing gnu-netcat so openbsd-netcat can get installed
- name: Ensure gnu-netcat in not installed
  community.general.pacman:
    name:
      - gnu-netcat
    state: absent
- name: Install libvirt packages
  community.general.pacman:
    name:
      - libvirt
      - qemu-full
      - dnsmasq
      - bridge-utils
      - openbsd-netcat
      - dmidecode
    state: present
  notify:
    - Reload libvirtd
