---
- name: Install libvirt packages
  pacman:
    name: 
      - libvirt
      - qemu-full
      - dnsmasq
      - bridge-utils
      - openbsd-netcat
      - dmidecode
    state:
      present
  notify:
    - reload libvirtd
