---
- name: Try to set debian_codename
  when:
    - ansible_lsb.codename is defined
  block:
    - name: Display ansible_lsb codename
      ansible.builtin.debug.debug:
        msg:
          - "codename: {{ ansible_lsb.codename }}"
      tags:
        - never
        - debug
    - name: Set debian_codename
      ansible.builtin.set_fact:
        debian_codename: "{{ ansible_lsb.codename }}"

- name: Install the required Debian packages
  ansible.builtin.include_tasks: "{{ install_debian }}"
  with_first_found:
    - Debian_os_family/{{ debian_codename }}.yml
    - Debian_os_family/defaults.yml
  loop_control:
    loop_var: install_debian
