---
- name: Try to set debian_codename
  block:
    - name: Display ansible_lsb codename
      debug:
        msg:
          - "codename: {{ ansible_lsb.codename }}"
      tags:
        - never
        - debug
    - name: Set debian_codename
      set_fact:
        debian_codename: "{{  ansible_lsb.codename }}"
  when:
    - ansible_lsb.codename is defined

- name: Install the required Debian packages
  include_tasks: '{{ install_debian }}'
  with_first_found:
    - 'Debian_os_family/{{ debian_codename }}.yml'
    - 'Debian_os_family/defaults.yml'
  loop_control:
    loop_var: install_debian
