---
- name: Install the 'Virtualization Host' environment group
  # The dnf module supports both yum and dnf now.
  # Still needs to be tested
  ansible.builtin.dnf:
    name: "@^Virtualization Host"
    state: present
  notify:
    - Reload libvirtd
