---
- name: Install the libvirt related packages
  community.general.zypper:
    name:
      - libvirt
      - qemu-kvm
      - patterns-openSUSE-kvm_server
    state: present
  notify:
    - Reload libvirtd
