---
- name: Install the libvirt packages
  ansible.builtin.apt:
    pkg:
      - qemu-system
      - libvirt-clients
      - libvirt-daemon-system
      - bridge-utils
  notify:
    - Reload libvirtd
